# Generated by Django 3.1.7 on 2021-03-28 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('num_starts', models.CharField(choices=[('1', 'Одна звезда'), ('2', 'Две звезды'), ('3', 'Три звезды'), ('4', 'Четыре звезды'), ('5', 'Пять звезд')], max_length=1, verbose_name='Рейтинг размещения')),
                ('accommodation_type', models.CharField(choices=[('1', 'Резорт'), ('2', 'Бутик-отель'), ('3', 'Апартаменты'), ('4', 'Апарт-отель'), ('5', 'Вилла'), ('6', 'Бизнес-отель'), ('7', 'Спа-отель'), ('8', 'Шале'), ('9', 'Лоджи'), ('0', 'Кемпинг'), ('11', 'Мотель'), ('12', 'Отели типа «постель и завтрак»'), ('13', 'Хостел')], max_length=2, verbose_name='Тип размещения')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationManager',
            fields=[
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчествво')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='Профиль')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты')),
                ('checkin', models.TimeField(default=datetime.time(12, 0), verbose_name='Время заезда')),
                ('checkout', models.TimeField(default=datetime.time(10, 0), verbose_name='Время выселения')),
                ('booking', models.BooleanField(default=False, verbose_name='Номер забронирован')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('area', models.DecimalField(blank=True, decimal_places=1, max_digits=3, verbose_name='Площадь комнаты')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('hotel', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.accommodationfacility', verbose_name='Отель')),
                ('tag', models.ManyToManyField(blank=True, to='main.Tag', verbose_name='Теги')),
            ],
        ),
        migrations.AddField(
            model_name='accommodationfacility',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accommodationmanager', verbose_name='Управляющий'),
        ),
    ]
