# Generated by Django 3.1.7 on 2021-03-29 18:00

from django.db import migrations, models


def set_my_defaults(apps, schema_editor):
    rooms = apps.get_model("main", "Room")

    for room in rooms.objects.all().iterator():
        room.rental = 1000.0
        room.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210329_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rental',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Аренда за сутки'),
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.AlterField(
            model_name='room',
            name='rental',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Аренда за сутки'),
        ),
    ]


