# Generated by Django 3.1.7 on 2021-03-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rental',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Аренда за сутки'),
        ),
    ]
