# Generated by Django 3.1.7 on 2021-05-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default='standart', max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
