# Generated by Django 3.1.7 on 2021-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210329_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationfacility',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
