# Generated by Django 3.1.7 on 2021-05-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_room_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationfacility',
            name='meta',
            field=models.TextField(blank=True, verbose_name='Мета тег (SEO)'),
        ),
    ]
