# Generated by Django 3.1.7 on 2021-04-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210401_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='tag',
            new_name='tags',
        ),
    ]
