# Generated by Django 3.1.7 on 2021-05-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_accommodationfacility_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='meta',
            field=models.TextField(blank=True, verbose_name='Мета тег (SEO)'),
        ),
    ]
