# Generated by Django 3.1.7 on 2021-04-06 10:52

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210405_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to='avatar/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodationfacility',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/'),
        ),
    ]
