# Generated by Django 3.1.7 on 2021-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210406_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18, max_length=3, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
