# Generated by Django 3.1.7 on 2021-04-11 16:12

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default='1970-01-01', validators=[main.validators.validate_age], verbose_name='День рождения'),
            preserve_default=False,
        ),
    ]
