# Generated by Django 3.1.7 on 2021-04-14 19:58

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210411_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='images/'),
        ),
    ]
