# Generated by Django 3.1.7 on 2021-04-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_room_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(max_length=1, verbose_name='Статус')),
                ('message', models.CharField(max_length=100, verbose_name='Сообщение')),
                ('response', models.TextField(verbose_name='Ответ')),
            ],
        ),
    ]
