# Generated by Django 3.1.7 on 2021-05-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210422_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('a', 'Arhived')], default='Draft', max_length=1, verbose_name='Статус'),
        ),
    ]
